default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: link_referral_development

staging:
  <<: *default
  database: link_referral_staging

test:
  <<: *default
  database: link_referral_test

production:
  <<: *default
  database: link_referral_production